'use strict';
const $=s=>document.querySelector(s);
const paths={arrow:'<path d="M3 12h18m-6-6 6 6-6 6"/>',external:'<path d="m6 18 12-12M7 6h11v11"/>',right:'<path d="m9 5 7 7-7 7"/>',x:'<path d="M6 6 18 18M6 18 18 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',home:'<path d="m3 10 9-8 9 8M5 8v14h6v-8h4v8h4V8"/>',grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',link:'<path d="m9 15 6-6M9 8 7 10a4 4 0 0 0 6 6l2-2M15 16l2-2a4 4 0 0 0-6-6L9 10"/>',network:'<circle cx="5" cy="12" r="3"/><circle cx="18" cy="4" r="3"/><circle cx="18" cy="20" r="3"/><path d="m8 10 7-4M8 14l7 4"/>',users:'<circle cx="8" cy="6" r="3"/><circle cx="18" cy="6" r="3"/><path d="M2 22v-6a6 6 0 0 1 12 0v6H2ZM16 11c4-1 7 2 7 5v6h-7"/>',user:'<circle cx="12" cy="6" r="4"/><path d="M3 22v-3a9 9 0 0 1 18 0v3H3Z"/>',code:'<path d="m7 6-5 6 5 6M17 6l5 6-5 6M14 2l-4 20"/>',shield:'<path d="m12 2 9 4v6c0 5-5 8-9 10-4-2-9-5-9-10V6l9-4Z"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',bell:'<path d="M6 8a6 6 0 0 1 12 0v7l3 4H3l3-4V8ZM10 22h4"/>',help:'<circle cx="12" cy="12" r="10"/><path d="M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4M12 18h.01"/>',doc:'<path d="M4 2h11l5 5v15H4V2ZM15 2v5h5M8 11h8M8 15h8M8 19h5"/>',db:'<ellipse cx="12" cy="4" rx="9" ry="3"/><path d="M3 4v16c0 4 18 4 18 0V4M3 10c0 4 18 4 18 0M3 15c0 4 18 4 18 0"/>',sun:'<path d="M12 1v22M1 12h22M4 4l16 16M4 20 20 4M8 1l8 22M1 16l22-8M1 8l22 8M8 23 16 1"/>',chat:'<path d="M3 3h18v14H10l-7 5V3ZM7 7h10M7 12h7"/>',download:'<path d="M12 2v14m-5-5 5 5 5-5M3 16v6h18v-6"/>'};
function icon(name){return `<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]||paths.doc}</svg>`;}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const items=[
 {id:'design',name:'KYA Design System',type:'Skill',owner:'Communication',glyph:'Aa',state:'Mise à jour',tone:'orange',action:'Consulter',description:'Les règles, composants et ressources de marque pour concevoir des interfaces KYA cohérentes.',files:['SKILL.md','design.md','assets / logos','references / composants']},
 {id:'mcp',name:'KYA-Platform MCP',type:'MCP',owner:'Équipe plateforme',glyph:'network',state:'Configuré',action:'Gérer',description:'Accédez aux capacités autorisées depuis vos clients IA. Choisissez les outils que vous souhaitez exposer.',files:['Catalogue des outils','Périmètres d’accès','Documentation de connexion']},
 {id:'frappe',name:'Frappe',type:'App',owner:'Gestion métier',glyph:'F',state:'Externe',tone:'neutral',action:'Ouvrir',description:'Application métier externe référencée dans KYA-Platform. Le prototype ne lance aucune session réelle.',files:['Fiche de l’application','Responsable métier','Documentation']},
 {id:'documents',name:'Documents KYA',type:'Skill',owner:'Communication',glyph:'doc',state:'Disponible',action:'Consulter',description:'Modèles et consignes de rédaction pour produire les documents de l’entreprise.',files:['SKILL.md','Modèles de documents','Références de marque']},
 {id:'clients',name:'Référentiel clients',type:'Données',owner:'Groupe',glyph:'db',state:'Lecture',tone:'neutral',action:'Consulter',description:'Référentiel partagé dont les données visibles dépendent du contexte et des autorisations.',files:['Contrat de données','Provenance','Politique d’accès']}
];
let filter='all',query='',view='home',returnSelector='',toastTimer;
const toolState={search:true,read:true,export:false};
function render(){const result=items.filter(i=>(filter==='all'||i.type===filter)&&`${i.name} ${i.type} ${i.owner}`.toLocaleLowerCase('fr').includes(query));$('#resources').innerHTML=result.map(i=>`<div class="resource"><button class="resource-main" data-item="${i.id}" aria-label="Voir ${i.name}"><span class="resource-symbol ${['Aa','F'].includes(i.glyph)?'letter':''}">${['Aa','F'].includes(i.glyph)?i.glyph:icon(i.glyph)}</span><span><strong>${i.name}</strong><small>${i.type} · ${i.owner}</small><span class="compact-state">${i.state}</span></span></button><span class="state"><b class="dot ${i.tone||''}"></b>${i.state}</span><button class="outline resource-action" data-item="${i.id}" aria-label="${i.action} ${i.name}">${i.action}${i.id==='design'?'':icon(i.id==='frappe'?'external':'arrow')}</button></div>`).join('');$('#empty').hidden=result.length>0;}
function remember(){const el=document.activeElement;if($('#drawer').contains(el))return;if(el.id)returnSelector=`#${el.id}`;else if(el.dataset.item){const cls=el.classList.contains('resource-main')?'.resource-main':el.classList.contains('resource-action')?'.resource-action':'.pinned button';returnSelector=`${cls}[data-item="${el.dataset.item}"]`;}else if(el.dataset.panel)returnSelector=`[data-panel="${el.dataset.panel}"]`;else returnSelector='';}
function openDetail(html){remember();$('#detail').innerHTML=html;if(!$('#drawer').open)$('#drawer').showModal();document.body.style.overflow='hidden';$('#detail-title').focus({preventScroll:true});}
function closeDetail(){if($('#drawer').open)$('#drawer').close();}
$('#drawer').addEventListener('close',()=>{document.body.style.overflow='';const el=returnSelector&&$(returnSelector);if(el&&el.getClientRects().length)el.focus({preventScroll:true});else $('.menu-toggle').focus({preventScroll:true});});
$('#drawer').addEventListener('click',e=>{if(e.target!==$('#drawer'))return;const r=$('#drawer').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDetail();});
$('#close').onclick=closeDetail;
function title(text){return `<h2 id="detail-title" tabindex="-1">${text}</h2>`;}
function list(lines){return `<ul class="detail-files">${lines.map(t=>`<li>${icon('doc')}<span>${t}</span></li>`).join('')}</ul>`;}
function showItem(id){const i=items.find(x=>x.id===id);openDetail(`${title(i.name)}<small>${i.type} · ${i.owner} · ${i.state}</small>${i.id==='design'?'<div class="palette" aria-label="Couleurs officielles KYA"><span title="#1CA18C"></span><span title="#F99D32"></span><span title="#E8E748"></span><span title="#875028"></span></div>':''}<p>${i.description}</p><section class="detail-meta"><p><strong>Contexte</strong><br>${$('#entity').value} · ${$('#unit').value}</p>${i.type==='Skill'?'<p><strong>Version illustrée</strong> · 0.2.0<br>Responsable · Communication</p>':''}</section><h3>${i.type==='Skill'?'Contenu du package':'Ressources'}</h3>${list(i.files)}${i.id==='mcp'?`<h3>Outils exposés — démonstration</h3>${Object.entries({search:'Rechercher des contenus',read:'Lire les sources autorisées',export:'Exporter les résultats'}).map(([key,label])=>`<label class="check-option"><input type="checkbox" data-tool="${key}" ${toolState[key]?'checked':''}>${label}</label>`).join('')}`:''}<div class="detail-actions"><button class="primary" data-simulate="${i.id==='mcp'?'Configuration enregistrée localement':i.type==='Skill'?'Téléchargement simulé':i.type==='App'?'Ouverture externe simulée':'Consultation simulée'}">${i.type==='Skill'?icon('download'):''}${i.type==='Skill'?'Télécharger le package':i.id==='mcp'?'Enregistrer mes choix':i.type==='App'?'Ouvrir l’application':'Consulter les données'}</button><button class="text-action" data-panel="help">Guide d’utilisation${icon('external')}</button></div>`);}
const panels={
 requests:['À traiter','Deux exemples pour valider le parcours de revue.',['Mise à jour · KYA Design System 0.2.0','Demande d’accès · Référentiel clients']],
 changes:['Version 0.2.0','Exemple de mise à jour à examiner.',['Typographie et formes des composants','Palette KYA sur fond clair','Ressources et logos officiels']],
 access:['Demande d’accès','Équipe Applications · Référentiel clients. Exemple illustratif, sans données personnelles réelles.',['Droit demandé : lecture','Périmètre : unité active','Décision : à examiner']],
 spaces:['Espaces','Les espaces regroupent les capacités, membres et contributions d’une équipe ou d’un projet.',['Direction des Systèmes','Communication','Espace stagiaires']],
 studio:['Studio','Créer, tester et publier des capacités à partir des templates maîtres.',['Créer un skill ou un MCP','Préparer les fichiers et médias','Exécuter les tests','Soumettre une version pour validation']],
 admin:['Administration du socle','Une administration distincte des usages personnels.',['Organisation et affectations','Identités et accès','Espaces et partage','Référentiels Core','Données et ingestion','Registre et gouvernance','Intégrations et secrets','Exploitation et audit']],
 profile:['Jean-Claude','Compte de démonstration. Le changement de contexte ne modifie aucun droit réel.',['Profil illustré : CVSI','Les permissions réelles restent évaluées côté serveur.']],
 help:['Maquette interactive','Ce prototype est indépendant de l’application réelle.',['Rechercher et filtrer les capacités','Ouvrir les fiches et changer de contexte','Tester les options MCP en mémoire','Échap ferme le panneau · Ctrl K ouvre la recherche']]
};
function showPanel(name){if(name==='menu'){openDetail(`${title('Navigation')}<div class="nav-list"><button data-view="home">Accueil</button><button data-view="catalog">Catalogue</button><button data-panel="connections">Mes connexions</button><button data-panel="spaces">Espaces</button><button data-panel="studio">Studio</button><button data-panel="admin">Administration</button></div>`);return;}if(name==='connections'){openDetail(`${title('Mes connexions')}<p>État de démonstration. Aucun client n’a été connecté par cette maquette.</p>${['Claude','ChatGPT','Codex'].map((client,index)=>`<button class="dialog-client" data-panel="${client.toLowerCase()}">${client}<small>${index?'Configurer':'Connecté (démo)'}${icon('right')}</small></button>`).join('')}`);return;}if(['claude','chatgpt','codex'].includes(name)){const client={claude:'Claude',chatgpt:'ChatGPT',codex:'Codex'}[name];openDetail(`${title(client)}<p>${name==='claude'?'État connecté illustratif.':'Configurer votre accès depuis votre environnement externe.'}</p><h3>Parcours de connexion</h3>${list(['Ajouter KYA-Platform dans votre client','Vous authentifier avec votre compte','Vérifier le contexte et les autorisations','Choisir les outils à exposer'])}<div class="detail-actions"><button class="outline" data-item="mcp">Configurer les outils${icon('arrow')}</button></div>`);return;}const [heading,body,lines]=panels[name];openDetail(`${title(heading)}<p>${body}</p><section class="detail-meta">${list(lines)}</section>${name==='changes'?'<div class="detail-actions"><button class="outline" data-item="design">Voir le skill</button></div>':''}`);}
function notify(message){$('#toast').textContent=`${message} — aucune action externe.`;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),5000);}
function setFilter(value){filter=value;document.querySelectorAll('[data-filter]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.filter===value));b.tabIndex=b.dataset.filter===value?0:-1;if(b.dataset.filter===value)$('#resources').setAttribute('aria-labelledby',b.id);});render();}
function setView(name){view=name;closeDetail();$('#page-title').textContent=name==='catalog'?'Catalogue':'Mon espace';$('#capabilities-title').textContent=name==='catalog'?'Catalogue autorisé':'Mes capacités';document.querySelectorAll('.sidebar [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===name);if(b.dataset.view===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});query='';$('#search').value='';setFilter('all');if(name==='catalog')$('#search').focus();}
document.addEventListener('click',e=>{const item=e.target.closest('[data-item]'),panel=e.target.closest('[data-panel]'),tab=e.target.closest('[data-filter]'),nav=e.target.closest('[data-view]'),simulation=e.target.closest('[data-simulate]');if(item)showItem(item.dataset.item);else if(panel)showPanel(panel.dataset.panel);else if(tab)setFilter(tab.dataset.filter);else if(nav)setView(nav.dataset.view);else if(simulation){notify(simulation.dataset.simulate);let status=$('#drawer-status');if(!status){status=document.createElement('p');status.id='drawer-status';status.role='status';$('#detail').append(status);}status.textContent=simulation.dataset.simulate+' — démonstration, aucune action réelle.';}});
document.addEventListener('change',e=>{if(e.target.matches('[data-tool]'))toolState[e.target.dataset.tool]=e.target.checked;});
$('#search').oninput=e=>{query=e.target.value.trim().toLocaleLowerCase('fr');render();};$('#reset').onclick=()=>{query='';$('#search').value='';setFilter('all');$('#search').focus();};
$('#unit').onchange=()=>{$('#hero-unit').textContent=$('#unit').value;notify('Contexte visuel mis à jour');};$('#entity').onchange=()=>notify('Entité de démonstration sélectionnée');
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();returnSelector='#search';closeDetail();$('#search').focus();}if(e.target.matches('[role="tab"]')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[role="tab"]')],index=tabs.indexOf(e.target),next=e.key==='Home'?tabs[0]:e.key==='End'?tabs.at(-1):tabs[(index+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length];setFilter(next.dataset.filter);next.focus();}});
render();
