import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const output=new URL('./verification/',import.meta.url);
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1586,height:992},deviceScaleFactor:1});
const errors=[],failed=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)failed.push(`${r.status()} ${r.url()}`);});
await page.goto('http://127.0.0.1:4195/kya-signature/index.html');
await page.evaluate(()=>document.fonts.ready);
await page.locator('.hero-photo').evaluate(img=>img.decode());
await page.screenshot({path:fileURLToPath(new URL('desktop.png',output)),fullPage:true});
assert.equal(await page.locator('.resource').count(),5);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.getByRole('tab',{name:'Skills',exact:true}).click();
assert.equal(await page.locator('.resource').count(),2);
await page.keyboard.press('ArrowRight');
assert.equal(await page.getByRole('tab',{name:'Données',exact:true}).getAttribute('aria-selected'),'true');
await page.getByRole('tab',{name:'Tout',exact:true}).click();
await page.locator('#search').fill('solaire-introuvable');
assert.equal(await page.locator('#empty').isVisible(),true);
await page.locator('#reset').click();
await page.locator('#search').fill('clients');
assert.equal(await page.locator('.resource').count(),1);
await page.locator('#search').fill('');
await page.locator('.resource-action[data-item="mcp"]').click();
assert.equal(await page.locator('#drawer').isVisible(),true);
assert.equal(await page.locator('#detail-title').evaluate(e=>e===document.activeElement),true);
await page.locator('[data-tool="export"]').check();
await page.locator('[data-simulate]').click();
assert.match(await page.locator('#drawer-status').textContent(),/aucune action réelle/);
await page.keyboard.press('Escape');
assert.equal(await page.locator('.resource-action[data-item="mcp"]').evaluate(e=>e===document.activeElement),true);
await page.locator('.resource-action[data-item="mcp"]').click();
assert.equal(await page.locator('[data-tool="export"]').isChecked(),true);
await page.keyboard.press('Escape');
await page.locator('#unit').selectOption({label:'Communication'});
assert.equal(await page.locator('#hero-unit').textContent(),'Communication');
await page.locator('#unit').selectOption({label:'Direction des Systèmes'});
await page.getByRole('button',{name:'Voir KYA Design System',exact:true}).click();
await page.screenshot({path:fileURLToPath(new URL('desktop-detail.png',output))});
await page.keyboard.press('Control+k');
assert.equal(await page.locator('#search').evaluate(e=>e===document.activeElement),true);
await page.setViewportSize({width:390,height:844});
await page.reload();
await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.equal(await page.locator('#unit').isVisible(),true);
assert.equal(await page.locator('.compact-state').first().isVisible(),true);
await page.screenshot({path:fileURLToPath(new URL('mobile.png',output)),fullPage:true});
await page.getByRole('button',{name:'Ouvrir la navigation'}).click();
assert.equal(await page.locator('#drawer').isVisible(),true);
await page.locator('#drawer [data-panel="connections"]').click();
assert.equal(await page.locator('#detail-title').textContent(),'Mes connexions');
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Voir KYA Design System',exact:true}).click();
await page.screenshot({path:fileURLToPath(new URL('mobile-detail.png',output))});
await page.locator('#close').click();
assert.equal(await page.getByRole('button',{name:'Voir KYA Design System',exact:true}).evaluate(e=>e===document.activeElement),true);
assert.deepEqual(errors,[]);
assert.deepEqual(failed,[]);
console.log('PASS: desktop/mobile layout, asset loading, filters, search, contexts, dialogs, focus, keyboard navigation and simulated MCP preferences.');
await browser.close();
