export type StatusTone = 'healthy' | 'attention' | 'warning' | 'restricted' | 'neutral';

export type IconName =
  | 'apps'
  | 'activity'
  | 'bell'
  | 'branch'
  | 'catalog'
  | 'check'
  | 'chevron'
  | 'clock'
  | 'code'
  | 'command'
  | 'database'
  | 'deploy'
  | 'file'
  | 'folder'
  | 'governance'
  | 'home'
  | 'key'
  | 'lock'
  | 'network'
  | 'people'
  | 'plus'
  | 'search'
  | 'settings'
  | 'shield'
  | 'skill'
  | 'user';
