'use strict';
const $ = (s) => document.querySelector(s);
const icons = {plus:'<path d="M12 5v14M5 12h14"/>',x:'<path d="m6 6 12 12M6 18 12-12"/>',arrow:'<path d="M4 12h16m-5-5 5 5-5 5"/>',external:'<path d="M8 16 18 6M9 6h9v9"/>',book:'<path d="M12 5c-3-2-6-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1v15"/>',edit:'<path d="m4 16 12-12 4 4L8 20H4v-4ZM14 6l4 4"/>',send:'<path d="m3 10 18-7-7 18-4-7-7-4Zm7 4L21 3"/>',db:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>',chat:'<path d="M4 4h16v12H9l-5 4V4Z"/><path d="M8 8h8M8 12h5"/>'};
icons.x='<path d="M6 6 18 18M6 18 18 6"/>';
function icon(name){return `<svg aria-hidden="true" viewBox="0 0 24 24">${icons[name] || `<use href="../kya-command/icons.svg#${name}"/>`}</svg>`;}
function hydrate(){document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);el.removeAttribute('data-icon');});}
const items=[
 {id:'design',name:'KYA Design System',type:'Skill',owner:'Communication',glyph:'Aa',state:'Mise à jour',action:'',description:'Les règles et ressources pour concevoir des interfaces cohérentes avec KYA.',files:['SKILL.md','design.md','Logos officiels','Références UI']},
 {id:'mcp',name:'KYA-Platform MCP',type:'MCP',owner:'Équipe plateforme',glyph:'link',state:'Configuré',action:'Gérer',description:'Choisissez les outils à exposer dans votre environnement IA. Les autorisations restent limitées à votre contexte actif.',files:['Catalogue des outils','Outils activés','Périmètre des données']},
 {id:'frappe',name:'Frappe',type:'App',owner:'Gestion métier',glyph:'F',state:'Externe',action:'Ouvrir',description:'Application métier externe référencée par KYA-Platform. Cette maquette ne lance aucune session réelle.',files:['Fiche de l’application','Responsable métier','Documentation']},
 {id:'documents',name:'Documents KYA',type:'Skill',owner:'Communication',glyph:'doc',state:'Disponible',action:'Consulter',description:'Modèles et consignes pour produire des documents cohérents avec la charte de l’entreprise.',files:['SKILL.md','Modèles de documents','Règles de rédaction']},
 {id:'clients',name:'Référentiel clients',type:'Données',owner:'Groupe',glyph:'db',state:'Lecture autorisée',action:'Consulter',description:'Référentiel partagé de clients. Les données visibles dépendent des autorisations de votre unité.',files:['Contrat de données','Provenance','Politique d’accès']}
];
let active='design',filter='all',query='',organizing=false,pinned=['frappe','documents','mcp'],toastTimer,lastTrigger,returnSelector='',booting=true;
function rememberTrigger(){if($('#inspector').contains(document.activeElement))return;lastTrigger=document.activeElement;const e=lastTrigger;if(e.id)returnSelector=`#${e.id}`;else if(e.dataset.item){const kind=e.classList.contains('pinned-item')?'pinned-item':e.classList.contains('resource-action')?'resource-action':'resource-main';returnSelector=`.${kind}[data-item="${e.dataset.item}"]`;}else if(e.dataset.info)returnSelector=`[data-info="${e.dataset.info}"]`;else returnSelector='';}
function glyph(item){return `<span class="resource-icon">${['Aa','F'].includes(item.glyph)?item.glyph:icon(item.glyph)}</span>`;}
function render(){const visible=items.filter(i=>(filter==='all'||i.type===filter)&&`${i.name} ${i.type} ${i.owner}`.toLocaleLowerCase('fr').includes(query));$('#count').textContent=visible.length;$('#empty').hidden=visible.length>0;$('#resources').innerHTML=visible.map(i=>`<div class="resource ${active===i.id&&!document.body.classList.contains('no-inspector')?'selected':''}"><button class="resource-main" data-item="${i.id}" aria-label="Voir ${i.name}">${glyph(i)}<span><strong>${i.name}</strong><small>${i.type} · ${i.owner}</small></span></button><span class="state">${i.id==='design'?'<span class="dot amber"></span>':''}${i.state}</span><button class="resource-action" data-item="${i.id}" aria-label="${i.action||'Voir'} ${i.name}">${i.action}${icon(i.id==='design'?'right':i.id==='frappe'?'external':'arrow')}</button></div>`).join('');renderPins();}
function renderPins(){$('#pinned').innerHTML=pinned.map(id=>{const i=items.find(x=>x.id===id);return `<button class="pinned-item" ${organizing?`data-unpin="${id}"`:`data-item="${id}"`}>${glyph(i)}<span><strong>${i.name}</strong><small>${organizing?'Retirer':id==='frappe'?'Ouvrir':id==='mcp'?'Gérer les outils':'Voir le skill'}${icon(organizing?'x':id==='frappe'?'external':'arrow')}</small></span></button>`;}).join('')||'<p class="detail-note">Aucun épinglé. Cliquez sur « Terminer » pour restaurer les raccourcis de démonstration.</p>';}
function scope(){return $('#unit').value;}
function openInspector(){document.body.classList.remove('no-inspector');$('#navigation').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');syncOverlay();}
function showItem(id){lastTrigger=document.activeElement;active=id;const i=items.find(x=>x.id===id);$('#detail').innerHTML=`<span class="detail-type">${i.type}</span><h2 tabindex="-1">${i.name}</h2><p class="owner">${i.owner}${i.id==='design'?' · CVSI':''}</p>${i.id==='design'?'<div class="swatches" aria-label="Palette de marque KYA"><span class="type-preview">Aa</span><span class="swatch teal" title="#1CA18C"></span><span class="swatch orange" title="#F99D32"></span><span class="swatch yellow" title="#E8E748"></span><span class="swatch coffee" title="#875028"></span></div>':''}<p class="description">${i.description}</p><section class="detail-section"><div class="access">${icon('lock')}<div>Disponible dans votre unité<small>${scope()}</small></div></div>${i.type==='Skill'?'<dl class="versions"><div><dt>Version proposée</dt><dd>0.2.0</dd></div><div><dt>Votre version</dt><dd>0.1.0</dd></div></dl>':''}</section><section class="detail-section"><h3>${i.type==='Skill'?'Dans ce package':'Ressources'}</h3><ul class="files">${i.files.map(f=>`<li>${icon('doc')}${f}</li>`).join('')}</ul></section><div class="detail-actions"><button class="text-link" data-info="changes">${i.type==='Skill'?'Voir les changements':'Voir les détails'}${icon('arrow')}</button><button class="button primary" data-demo-action="${i.type==='Skill'?'Téléchargement':i.type==='MCP'?'Configuration':i.type==='App'?'Ouverture externe':'Consultation'}">${icon(i.type==='Skill'?'down':'external')}${i.type==='Skill'?'Télécharger le package':i.type==='MCP'?'Configurer les outils':i.type==='App'?'Ouvrir l’application':'Consulter les données'}</button><button class="text-link" data-info="help">Guide d’utilisation${icon('external')}</button></div>`;openInspector();render();}
const info={
 requests:['À examiner','Deux exemples de demandes pour visualiser le parcours.',['Mise à jour · KYA Design System 0.2.0','Accès · Équipe Applications / Référentiel clients']],
 admin:['Administration du socle','Une entrée dédiée à la gouvernance, distincte des capacités personnelles.',['Organisation et affectations','Identités, rôles et autorisations','Données et contrats','Intégrations et secrets','Registre, versions et audit']],
 studio:['Studio','La fabrique des capacités. Cet écran de travail fera l’objet d’une validation dédiée.',['Créer à partir d’un template','Préparer les fichiers et ressources','Exécuter les contrôles','Soumettre pour validation']],
 publications:['Publications','Suivre les versions et les validations avant leur mise à disposition.',['Brouillons','En validation','Versions publiées']],
 profile:['Jean-Claude','Contexte de démonstration — aucun droit réel n’est modifié.',['Profil : CVSI','Les droits sont évalués côté serveur dans l’application réelle.']],
 help:['À propos de cette maquette','Prototype visuel autonome, sans appel au backend et sans manipulation de secrets.',['Les filtres, la recherche et les détails fonctionnent localement.','Les accès, connexions et versions sont illustratifs.','Échap ferme le panneau. Ctrl K ouvre la recherche.']],
 changes:['Changements proposés','Version 0.2.0 — contenu illustratif pour valider l’expérience.',['Typographie et hiérarchie','Composants et états interactifs','Logos et ressources de marque']],
 claude:['Connexion à Claude','État connecté illustratif. Aucune connexion réelle n’a été établie par ce prototype.',['Gérer les outils MCP exposés','Vérifier les autorisations','Révoquer une connexion depuis l’application réelle']],
 chatgpt:['Connecter ChatGPT','Le parcours final utilise les capacités du client et le mécanisme d’autorisation de KYA-Platform.',['Ajouter le connecteur KYA-Platform dans votre client','Se connecter et vérifier le contexte','Autoriser les capacités souhaitées']],
 codex:['Connecter Codex','Utilisez le MCP dans votre environnement de développement.',['Configurer le serveur MCP','S’authentifier avec son compte','Choisir ses outils et ressources']]
};
function showInfo(key){lastTrigger=document.activeElement;const [title,description,lines]=info[key];active=null;$('#detail').innerHTML=`<span class="detail-type">Prototype</span><h2 tabindex="-1">${title}</h2><p class="description">${description}</p><ul class="info-list">${lines.map(l=>`<li>${l}</li>`).join('')}</ul><p class="detail-note">Les actions réelles seront raccordées après validation du design.</p>`;openInspector();render();$('#detail h2').focus({preventScroll:true});}
function closeInspector(){document.body.classList.add('no-inspector');syncOverlay();render();const target=returnSelector?$(returnSelector):lastTrigger;if(target?.isConnected)target.focus({preventScroll:true});}
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function syncOverlay(){const drawer=innerWidth<=1000&&!document.body.classList.contains('no-inspector'),menu=innerWidth<=760&&$('#navigation').classList.contains('open'),overlay=drawer||menu;$('#scrim').hidden=!overlay;$('#main').inert=overlay;$('.topbar').inert=overlay;$('#navigation').inert=drawer||(innerWidth<=760&&!menu);$('#inspector').inert=menu;document.body.style.overflow=overlay?'hidden':'';if(drawer){$('#inspector').setAttribute('role','dialog');$('#inspector').setAttribute('aria-modal','true');}else{$('#inspector').removeAttribute('role');$('#inspector').removeAttribute('aria-modal');}}
// Preserve a stable return target when rendering replaces the selected row.
const renderItemDetail=showItem,renderInfoDetail=showInfo;
showItem=function(id){rememberTrigger();renderItemDetail(id);if(!booting)$('#detail h2').focus({preventScroll:true});};
showInfo=function(key){rememberTrigger();renderInfoDetail(key);};
function page(name){document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===name);if(b.dataset.page===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('#page-title').textContent={home:'Mon espace',capabilities:'Mes capacités',catalog:'Catalogue',connections:'Mes connexions'}[name];filter='all';query='';$('#search').value='';setFilter('all');$('#navigation').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');if(name==='connections'){$('#connections').scrollIntoView({behavior:'smooth',block:'center'});showInfo('claude');}else closeInspector();}
function setFilter(value){filter=value;document.querySelectorAll('[data-filter]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.filter===value);b.tabIndex=b.dataset.filter===value?0:-1;});render();}
document.addEventListener('click',e=>{const item=e.target.closest('[data-item]'),information=e.target.closest('[data-info]'),tab=e.target.closest('[data-filter]'),nav=e.target.closest('[data-page]'),action=e.target.closest('[data-demo-action]'),unpin=e.target.closest('[data-unpin]');if(item)showItem(item.dataset.item);if(information)showInfo(information.dataset.info);if(tab)setFilter(tab.dataset.filter);if(nav)page(nav.dataset.page);if(action)notify(`${action.dataset.demoAction} simulé : aucune action externe ni modification réelle.`);if(unpin){pinned=pinned.filter(id=>id!==unpin.dataset.unpin);renderPins();}});
$('#search').addEventListener('input',e=>{query=e.target.value.trim().toLocaleLowerCase('fr');render();});$('#close').onclick=closeInspector;
$('#reset').onclick=()=>{query='';$('#search').value='';setFilter('all');};$('#add').onclick=()=>{page('catalog');notify('Catalogue de démonstration : sélectionnez une capacité pour consulter son détail.');$('#search').focus();};$('#all').onclick=()=>page('capabilities');
$('#organize').onclick=()=>{organizing=!organizing;$('#organize').textContent=organizing?'Terminer':'Organiser';if(!organizing&&!pinned.length)pinned=['frappe','documents','mcp'];renderPins();};
$('#unit').onchange=()=>{const limited=scope()==='Espace stagiaires';$('.administration').hidden=limited;$('#role').textContent=limited?'Profil stagiaire (démo)':'Profil CVSI';if(active)showItem(active);notify('Contexte visuel modifié. Les autorisations de cette maquette restent simulées.');};$('#entity').onchange=()=>{notify('Entité de démonstration sélectionnée. Aucune donnée réelle n’est chargée.');};
$('#menu').onclick=()=>{rememberTrigger();const opened=$('#navigation').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(opened));if(opened)document.body.classList.add('no-inspector');syncOverlay();if(opened)$('#navigation button').focus();};$('#scrim').onclick=()=>{$('#navigation').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');closeInspector();};
document.addEventListener('keydown',e=>{if(e.key!=='Tab'||$('#scrim').hidden)return;const area=$('#navigation').classList.contains('open')?$('#navigation'):$('#inspector'),focusable=[...area.querySelectorAll('button:not(:disabled),a[href],input,select,[tabindex="0"]')].filter(el=>el.getClientRects().length>0),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||!focusable.includes(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus();}if(e.key==='Escape'){$('#navigation').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');closeInspector();}if(e.target.matches('[role="tab"]')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[role="tab"]')],i=tabs.indexOf(e.target),next=tabs[(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length];setFilter(next.dataset.filter);next.focus();}});
window.addEventListener('resize',syncOverlay);
hydrate();showItem('design');setFilter('all');if(innerWidth<=1000)closeInspector();booting=false;
