import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const output = new URL('./verification/', import.meta.url);
await mkdir(output, {recursive:true});
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1586,height:992},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4195/kya-essential/index.html');
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:new URL('desktop.png',output).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true});
assert.equal(await page.locator('.resource').count(),5);
await page.getByRole('tab',{name:'Skills',exact:true}).click();
assert.equal(await page.locator('.resource').count(),2);
await page.getByRole('tab',{name:'Tout',exact:true}).click();
await page.locator('#search').fill('aucune-capacite');
assert.equal(await page.locator('#empty').isVisible(),true);
await page.locator('#reset').click();
await page.getByRole('button',{name:'Fermer le détail'}).click();
assert.equal(await page.locator('#inspector').isVisible(),false);
await page.getByRole('button',{name:'Voir KYA-Platform MCP',exact:true}).click();
assert.equal(await page.locator('#detail h2').textContent(),'KYA-Platform MCP');
await page.getByRole('button',{name:'Fermer le détail'}).click();
assert.equal(await page.locator('.resource-main[data-item="mcp"]').evaluate(el=>el===document.activeElement),true);
await page.getByRole('button',{name:'Voir KYA-Platform MCP',exact:true}).click();
await page.locator('#unit').selectOption({label:'Communication'});
assert.equal(await page.locator('.access small').textContent(),'Communication');
await page.locator('#unit').selectOption({label:'Espace stagiaires'});
assert.equal(await page.locator('.administration').isVisible(),false);
await page.locator('#unit').selectOption({label:'Direction des Systèmes'});
await page.getByRole('button',{name:'Voir KYA Design System',exact:true}).first().click();
await page.locator('[data-demo-action]').click();
assert.match(await page.locator('#toast').textContent(),/simulé/);
await page.keyboard.press('Escape');
assert.equal(await page.locator('#inspector').isVisible(),false);
await page.keyboard.press('Control+k');
assert.equal(await page.locator('#search').evaluate(e=>e===document.activeElement),true);
await page.setViewportSize({width:390,height:844});
await page.reload();
await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('#navigation').evaluate(el=>el.inert),true);
await page.screenshot({path:new URL('mobile.png',output).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.getByRole('button',{name:'Voir KYA Design System',exact:true}).first().click();
assert.equal(await page.locator('#inspector').isVisible(),true);
assert.equal(await page.locator('#detail h2').evaluate(el=>el===document.activeElement),true);
assert.equal(await page.locator('#main').evaluate(el=>el.inert),true);
await page.locator('#detail button').last().focus();
await page.keyboard.press('Tab');
assert.equal(await page.locator('#close').evaluate(el=>el===document.activeElement),true);
await page.screenshot({path:new URL('mobile-detail.png',output).pathname.replace(/^\/(\w:)/,'$1')});
await page.getByRole('button',{name:'Fermer le détail'}).click();
assert.equal(await page.locator('#main').evaluate(el=>el.inert),false);
assert.equal(await page.getByRole('button',{name:'Voir KYA Design System',exact:true}).first().evaluate(el=>el===document.activeElement),true);
await page.getByRole('button',{name:'Ouvrir le menu'}).click();
assert.match(await page.locator('#navigation').getAttribute('class'),/open/);
assert.deepEqual(errors,[]);
console.log('PASS: interaction, layout, runtime and keyboard-overlay checks; desktop + mobile screenshots saved.');
await browser.close();
