"""Governed Registry MCP contracts and authorization."""

from kya_platform.mcp.registry.contracts import (
    ArtifactDetail,
    ArtifactSummary,
    Confirmation,
    ConfirmInstallationInput,
    ConfirmUpdateInput,
    GetArtifactInput,
    GetOperationInput,
    InstallationAction,
    InstallationRecorded,
    ListUpdatesInput,
    ListUpdatesOutput,
    ManageInstallationInput,
    OperationAccepted,
    OperationStatus,
    PublicationAccepted,
    PublishCandidateInput,
    RegistryRisk,
    RegistryTool,
    RequestInstallInput,
    RequestUpdateInput,
    SearchCatalogInput,
    SearchCatalogOutput,
    ToolAccessContext,
    ToolAuthorizer,
    UpdateSummary,
)

__all__ = [
    "ArtifactDetail",
    "ArtifactSummary",
    "ConfirmInstallationInput",
    "ConfirmUpdateInput",
    "Confirmation",
    "GetArtifactInput",
    "GetOperationInput",
    "InstallationAction",
    "InstallationRecorded",
    "ListUpdatesInput",
    "ListUpdatesOutput",
    "ManageInstallationInput",
    "OperationAccepted",
    "OperationStatus",
    "PublicationAccepted",
    "PublishCandidateInput",
    "RegistryRisk",
    "RegistryTool",
    "RequestInstallInput",
    "RequestUpdateInput",
    "SearchCatalogInput",
    "SearchCatalogOutput",
    "ToolAccessContext",
    "ToolAuthorizer",
    "UpdateSummary",
]
