"""Import every mapped model for Alembic discovery."""

from kya_platform.infrastructure.database.models.bootstrap import PlatformBootstrapClaim
from kya_platform.infrastructure.database.models.catalog import (
    CatalogArtifact,
    CatalogArtifactVersion,
    CatalogAttestation,
    CatalogCapabilityManifest,
    CatalogDistributionOperation,
    CatalogInstallation,
    CatalogInstallationHistory,
    CatalogPackageFile,
    CatalogPublicationRequest,
    CatalogRelease,
)
from kya_platform.infrastructure.database.models.core import (
    CoreClientAccount,
    CoreContactPoint,
    CoreExternalReference,
    CoreOrganizationalUnit,
    CoreOrganizationalUnitRelation,
    CoreOrganizationalUnitType,
    CoreParty,
    CorePersonProfile,
    CorePosition,
    CorePositionAssignment,
    CoreProject,
    CoreProjectSite,
    CoreSite,
    CoreWorkRelationship,
)
from kya_platform.infrastructure.database.models.data import (
    DataAssetRow,
    DataContentChunkRow,
    DataContentDocumentRow,
    DataContractVersionRow,
    DataIngestionRunRow,
    DataIngestionScheduleRow,
    DataLineageEdgeRow,
    DataPipelineRow,
    DataQualityResultRow,
    DataSnapshotRow,
    DataSourceFlowRow,
    DataSourceRow,
)
from kya_platform.infrastructure.database.models.identity import ExternalIdentity
from kya_platform.infrastructure.database.models.intelligence import (
    IntelligenceSignalRow,
    IntelligenceWatchRow,
)
from kya_platform.infrastructure.database.models.mcp_control import (
    McpToolDefinition,
    McpToolProfile,
    McpToolProfileAssignment,
    McpToolProfileItem,
    McpUserToolPreference,
)
from kya_platform.infrastructure.database.models.oauth import (
    OAuthClient,
    OAuthGrant,
    OAuthTokenRecord,
)
from kya_platform.infrastructure.database.models.reliability import (
    AuditEvent,
    IdempotencyRecord,
    OutboxEvent,
)
from kya_platform.infrastructure.database.models.secrets import SecretReferenceRow
from kya_platform.infrastructure.database.models.workspaces import (
    WorkspaceLinkedUnitRow,
    WorkspaceMembershipRow,
    WorkspaceRow,
)

__all__ = [
    "AuditEvent",
    "CatalogArtifact",
    "CatalogArtifactVersion",
    "CatalogAttestation",
    "CatalogCapabilityManifest",
    "CatalogDistributionOperation",
    "CatalogInstallation",
    "CatalogInstallationHistory",
    "CatalogPackageFile",
    "CatalogPublicationRequest",
    "CatalogRelease",
    "CoreClientAccount",
    "CoreContactPoint",
    "CoreExternalReference",
    "CoreOrganizationalUnit",
    "CoreOrganizationalUnitRelation",
    "CoreOrganizationalUnitType",
    "CoreParty",
    "CorePersonProfile",
    "CorePosition",
    "CorePositionAssignment",
    "CoreProject",
    "CoreProjectSite",
    "CoreSite",
    "CoreWorkRelationship",
    "DataAssetRow",
    "DataContentChunkRow",
    "DataContentDocumentRow",
    "DataContractVersionRow",
    "DataIngestionRunRow",
    "DataIngestionScheduleRow",
    "DataLineageEdgeRow",
    "DataPipelineRow",
    "DataQualityResultRow",
    "DataSnapshotRow",
    "DataSourceFlowRow",
    "DataSourceRow",
    "ExternalIdentity",
    "IdempotencyRecord",
    "IntelligenceSignalRow",
    "IntelligenceWatchRow",
    "McpToolDefinition",
    "McpToolProfile",
    "McpToolProfileAssignment",
    "McpToolProfileItem",
    "McpUserToolPreference",
    "OAuthClient",
    "OAuthGrant",
    "OAuthTokenRecord",
    "OutboxEvent",
    "PlatformBootstrapClaim",
    "SecretReferenceRow",
    "WorkspaceLinkedUnitRow",
    "WorkspaceMembershipRow",
    "WorkspaceRow",
]
